name: Deploy App
run-name: ${{ github.actor }} is running tests 🚀
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Install dependencies
        run: yarn install
      - name: Lint application
        run: yarn lint
  Testing-process:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Install dependencies
        run: yarn install
      - name: Test application
        run: yarn test
  Build:
    runs-on: ubuntu-latest
    needs: Testing-process
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn run build
      - name: Deploy
        run: echo deploy application