name: Deploy App
run-name: ${{ github.actor }} is running tests 🚀
on:
  push:
    branches:
      - main
#    paths-ignore:
#      - '.github/workflows/*'
env:
  GH_SECRET: 111
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Lint application
        run: yarn lint
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Test application
        run: yarn test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn run build
  Deploy:
    runs-on: ubuntu-latest
    needs: [Lint, Tests, Build]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Deploy app
        run: echo "${{ env.GH_SECRET }}"