name: Tests
run-name: ${{ github.actor }} is running tests 🚀
on: [push]
jobs:
  Testing-process:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3.5.3
      - name: Install dependencies
        run: yarn install
      - name: Test application
        run: yarn test